# Textbook Content API
This API defines the interfaces for textbook content management and interactive features.

```yaml
openapi: 3.0.1
info:
  title: Physical AI & Humanoid Robotics Textbook API
  description: API for managing and accessing textbook content, user profiles, and interactive features
  version: 1.0.0
  contact:
    name: Textbook Development Team
    email: textbook@physical-ai.org

servers:
  - url: https://my-textbook.pages.dev/api/v1
    description: Production server

paths:
  /chapters:
    get:
      summary: List all textbook chapters
      description: Retrieve a list of all textbook chapters with basic metadata
      parameters:
        - name: part
          in: query
          description: Filter by textbook part (e.g., "part-i", "part-ii")
          schema:
            type: string
        - name: status
          in: query
          description: Filter by publication status
          schema:
            type: string
            enum: [draft, review, published]
            default: published
      responses:
        '200':
          description: A list of textbook chapters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Chapter'
  
  /chapters/{chapterId}:
    get:
      summary: Get a specific chapter
      description: Retrieve detailed information about a specific textbook chapter
      parameters:
        - name: chapterId
          in: path
          required: true
          description: Unique identifier of the chapter
          schema:
            type: string
      responses:
        '200':
          description: Detailed information about the chapter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chapter'
        '404':
          description: Chapter not found
  
  /sections:
    get:
      summary: List sections within a chapter
      description: Retrieve a list of sections within a specific chapter
      parameters:
        - name: chapterId
          in: query
          required: true
          description: ID of the parent chapter
          schema:
            type: string
      responses:
        '200':
          description: A list of sections in the specified chapter
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Section'
  
  /sections/{sectionId}:
    get:
      summary: Get a specific section
      description: Retrieve detailed information about a specific textbook section
      parameters:
        - name: sectionId
          in: path
          required: true
          description: Unique identifier of the section
          schema:
            type: string
      responses:
        '200':
          description: Detailed information about the section
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Section'
        '404':
          description: Section not found

  /users/profile:
    get:
      summary: Get user profile
      description: Retrieve the authenticated user's profile information
      responses:
        '200':
          description: User profile information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
    put:
      summary: Update user profile
      description: Update the authenticated user's profile information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfileUpdate'
      responses:
        '200':
          description: Updated user profile information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
  
  /content/search:
    get:
      summary: Search textbook content
      description: Search through textbook content by keywords
      parameters:
        - name: q
          in: query
          required: true
          description: Search query
          schema:
            type: string
        - name: limit
          in: query
          description: Maximum number of results to return
          schema:
            type: integer
            default: 10
        - name: type
          in: query
          description: Type of content to search
          schema:
            type: string
            enum: [chapter, section, all]
            default: all
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      oneOf:
                        - $ref: '#/components/schemas/Chapter'
                        - $ref: '#/components/schemas/Section'
                  total:
                    type: integer
                    description: Total number of results available

  /interactions/chat:
    post:
      summary: Interact with the RAG chatbot
      description: Send a query to the RAG-based chatbot for textbook-related questions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: The user's question or query
                context:
                  type: string
                  description: Context for the query (e.g., current chapter)
                userId:
                  type: string
                  description: User ID for personalization
      responses:
        '200':
          description: Chatbot response
          content:
            application/json:
              schema:
                type: object
                required:
                  - response
                properties:
                  response:
                    type: string
                    description: The chatbot's response
                  sources:
                    type: array
                    description: Source chapters/sections referenced in the response
                    items:
                      type: string

  /content/personalization:
    get:
      summary: Get personalized content
      description: Retrieve content recommendations based on user profile
      responses:
        '200':
          description: Personalized content recommendations
          content:
            application/json:
              schema:
                type: object
                properties:
                  recommendedChapters:
                    type: array
                    items:
                      $ref: '#/components/schemas/Chapter'
                  suggestedSections:
                    type: array
                    items:
                      $ref: '#/components/schemas/Section'
    post:
      summary: Update personalization preferences
      description: Update the user's personalization settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                preferences:
                  type: object
                  description: Personalization settings
                  additionalProperties: true
      responses:
        '200':
          description: Updated personalization settings
          content:
            application/json:
              schema:
                type: object
                properties:
                  preferences:
                    $ref: '#/components/schemas/PersonalizationSettings'

  /content/translation:
    post:
      summary: Translate content
      description: Translate textbook content to another language (e.g., Urdu)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - contentId
                - targetLanguage
              properties:
                contentId:
                  type: string
                  description: ID of the content to translate
                targetLanguage:
                  type: string
                  description: Target language code (e.g., "ur", "es", "fr")
                userId:
                  type: string
                  description: User ID for personalization
      responses:
        '200':
          description: Translated content
          content:
            application/json:
              schema:
                type: object
                required:
                  - translatedContent
                properties:
                  translatedContent:
                    type: string
                    description: The translated content
                  language:
                    type: string
                    description: The target language code
                  originalContentId:
                    type: string
                    description: The ID of the original content

components:
  schemas:
    Chapter:
      type: object
      required:
        - id
        - title
        - number
        - slug
        - description
        - learningObjectives
        - sections
        - status
      properties:
        id:
          type: string
          description: Unique identifier for the chapter
        title:
          type: string
          description: Display title of the chapter
          example: "Introduction to Physical AI"
        number:
          type: integer
          description: Sequential number in the textbook
          example: 1
        slug:
          type: string
          description: URL-friendly identifier
          example: "introduction-to-physical-ai"
        description:
          type: string
          description: Brief summary of chapter content
        learningObjectives:
          type: array
          description: List of learning objectives for the chapter
          items:
            type: string
        prerequisites:
          type: array
          description: Prerequisites for this chapter
          items:
            type: string
        sections:
          type: array
          description: List of sections in the chapter
          items:
            $ref: '#/components/schemas/SectionRef'
        metadata:
          type: object
          description: Additional metadata (author, creation date, etc.)
          additionalProperties: true
        status:
          type: string
          description: Publication status
          enum: [draft, review, published, archived]
    
    Section:
      type: object
      required:
        - id
        - title
        - number
        - slug
        - content
        - chapterId
        - status
      properties:
        id:
          type: string
          description: Unique identifier for the section
        title:
          type: string
          description: Display title of the section
        number:
          type: integer
          description: Sequential number in the parent chapter
        slug:
          type: string
          description: URL-friendly identifier
        content:
          type: string
          description: The actual content in MDX format
        learningObjectives:
          type: array
          description: Learning objectives specific to this section
          items:
            type: string
        chapterId:
          type: string
          description: Reference to parent chapter
        metadata:
          type: object
          description: Additional metadata
          additionalProperties: true
        status:
          type: string
          description: Publication status
          enum: [draft, review, published, archived]

    SectionRef:
      type: object
      required:
        - id
        - title
        - number
        - slug
      properties:
        id:
          type: string
          description: Unique identifier for the section
        title:
          type: string
          description: Display title of the section
        number:
          type: integer
          description: Sequential number in the parent chapter
        slug:
          type: string
          description: URL-friendly identifier
        status:
          type: string
          description: Publication status
          enum: [draft, review, published, archived]

    UserProfile:
      type: object
      required:
        - id
        - email
        - createdAt
      properties:
        id:
          type: string
          description: Unique identifier for the user
        name:
          type: string
          description: User's name
        email:
          type: string
          description: User's email
          format: email
        educationLevel:
          type: string
          description: Academic level
          enum: [undergraduate, graduate, professional, other]
        background:
          type: string
          description: Technical background information
        interests:
          type: array
          description: Topics of interest
          items:
            type: string
        learningGoals:
          type: array
          description: Goals for using the textbook
          items:
            type: string
        preferences:
          type: object
          description: Personalization settings
          additionalProperties: true
        progress:
          type: object
          description: Tracking progress through content
          additionalProperties: true
        createdAt:
          type: string
          format: date-time
          description: Account creation date
        lastActive:
          type: string
          format: date-time
          description: Last time user interacted with the system

    UserProfileUpdate:
      type: object
      properties:
        name:
          type: string
          description: User's name
        educationLevel:
          type: string
          description: Academic level
          enum: [undergraduate, graduate, professional, other]
        background:
          type: string
          description: Technical background information
        interests:
          type: array
          description: Topics of interest
          items:
            type: string
        learningGoals:
          type: array
          description: Goals for using the textbook
          items:
            type: string
        preferences:
          type: object
          description: Personalization settings
          additionalProperties: true

    PersonalizationSettings:
      type: object
      description: User's personalization settings
      properties:
        language:
          type: string
          description: Preferred language
          default: "en"
        theme:
          type: string
          description: Preferred UI theme
          enum: [light, dark, auto]
          default: auto
        difficultyLevel:
          type: string
          description: Preferred content difficulty
          enum: [beginner, intermediate, advanced]
        contentFormat:
          type: string
          description: Preferred content format
          enum: [text, visual, interactive]
        showAdvancedContent:
          type: boolean
          description: Whether to show advanced content by default
          default: true
```